### ISSUE TITLE
Convert to contig-based assembly graph

### ISSUE THREAD

**Issue by LynnLy** [AndreLamurias/GraphMB#10]
Hi there,
I have an ONT assembly that has been polished extensively with both ONT and Illumina reads. However, the polishing was done on the contigs from Flye, not the edges. Re-polishing is something I'd like to avoid, plus I'd like to keep the results of Flye's contig formation and extension. So I understand I would need to do step "3. Convert assembly graph to contig-based graph if you want to use full contig instead of edges."

Is this something that you have done before or do you know any existing toolkits that would help with this?

Thanks,
Lynn

**Comment by AndreLamurias** [comment]
Hi Lynn,
Yes I have had this issue too, it is not ideal because GraphMB will work on a less granular version of the assembly graph. 
But I wrote this script to help with that: https://github.com/AndreLamurias/binning_workflows/blob/main/generate_contig_graph.py
It writes the graph to a file as a list of edges, it needs to be converted to GFA afterwards
Let me know if you have any issues, this is a use case that we still need to improve

**Comment by AndreLamurias** [comment]
This step is no longer necessary, version 0.1.5 can read the contig sequences and use the contig graph directly with option --contignodes
```bash
graphmb --assembly data/strong100/ --outdir results/strong100/ --assembly_name contigs.fasta --depth contig_depth.txt --contignodes
```
Please try with this version, either install from the wheel or from source (I will update the docker image soon too)

**Comment by LynnLy** [comment]
Thank you for adding that in! I just tried the newest version of GraphMB on my contigs, and it ran successfully.
